2016-08-10 09:15:42: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 09:15:42: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 09:15:57: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 10:17:27: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 10:31:20: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 10:49:34: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:43:50: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:43:50: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 11:49:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 14:23:25: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 14:46:25: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 14:46:58: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:03:30: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:10:03: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 15:11:11: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 15:14:56: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:31:40: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:34:03: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:35:35: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:36:59: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 15:38:32: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:39:11: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:41:59: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 15:42:50: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 15:48:26: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:48:26: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 15:48:37: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:48:37: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-08-10 15:48:38: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-08-10 15:48:38: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
