2018-04-16 08:51:14: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2018-04-16 08:52:49: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2018-04-16 08:52:49: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2018-04-16 08:52:49: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
